### ISSUE TITLE
建议改进推荐机制

### ISSUE THREAD

**Issue by lolicondsy** [gentlemansolo/JavRocket#21]
有两点建议，一是首页中间的推荐栏能否单独独立出来、做成无限滑动推送的信息流？现在数量较少，图片较小看起来不清楚；二是希望点进影片时参考jbusdriver，有一个“你可能喜欢”的相似影片推送横栏（jbusdriver的这个功能很准质量也不错）。

**Comment by gentlemansolo** [comment]
详情页面有“你可能喜欢的”这个栏目，首页推荐栏目前只是作为一个补充，来源与收藏和点击磁力的时候收集的，所以没有无限滑动的信息流。
