### ISSUE TITLE
三星8.0系统导入导出均崩溃

### ISSUE THREAD

**Issue by sun0827peng** [gentlemansolo/JavRocket#25]
作者您好，我本人使用三星8.0系统未root，测试多个版本导入就停止运行，到处就弹窗崩溃提示重新打开应用，权限检查过均已授权，原因也一直未找到，仅做一反馈，可能上个问题提到的云同步会更好一些吧，换机也会方便！

**Comment by gentlemansolo** [comment]
你的机型是多少，我查查

**Comment by sun0827peng** [comment]
S8+，我禁用了系统自带的文件管理，装的re管理器，你一提醒我解禁后导出成功了，谢谢！
