### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by blinkblink0** [gentlemansolo/JavRocket#26]
感谢开发者如此无私的做出这种软件，功能建议可以整理出破坏版的链接，万分感谢

**Comment by gentlemansolo** [comment]
破坏版？你的意思是骑兵破解的影片吗

**Comment by blinkblink0** [comment]
是的是的，当然只是期待
能有现在这个软件也特别感谢了

---原始邮件---
发件人: "Gentleman"<notifications@github.com&gt;
发送时间: 2020年7月22日(周三) 下午5:45
收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;;
主题: Re: [gentlemansolo/JavRocket] 功能建议 (#26)




 
破坏版？你的意思是骑兵破解的影片吗

**Comment by gentlemansolo** [comment]
这个得有资源，你有相关的资源吗
