### ISSUE TITLE
能否在作品详情里增加系列信息

### ISSUE THREAD

**Issue by Eclocksss** [gentlemansolo/JavRocket#31]
为什么能搜索系列，却在特定作品的详情里无法直接搜索当前系列呢？或者退而求其次，能增加长按标题，选词进行搜索也好（直接查看系列好像会漏掉该系列的第一部，直接搜索系列名倒是能搜全）

**Comment by Eclocksss** [comment]
抱歉，作品详情里是有系列信息的，但是每个系列的第一部作品里不会显示系列信息，在系列里也找不到该系列的第一部作品。如果能支持查找到系列第一部作品就好了

**Comment by gentlemansolo** [comment]
你举个例子和番号我看看
