### ISSUE TITLE
出现无法加载封面的现象

### ISSUE THREAD

**Issue by liuyicen1** [gentlemansolo/JavRocket#33]
封面无法加载，代理为香港ip，内容图和视频预览均正常

**Comment by gthanmon** [comment]
我也出现了 而且我的预览图也不正常

**Comment by BbQ4466** [comment]
同上

**Comment by blinkblink0** [comment]
大佬，现在更新了好像还是打不开，图片也显示不了

**Comment by 1458271** [comment]
![Screenshot_20200806_000423](https://user-images.githubusercontent.com/24778221/89436622-11ed4b00-d779-11ea-9e96-79ef06f923a7.jpg)
打开兼容模式后大部分图片显示都没有问题了，唯独这个“你可能也喜欢”里面的图片显示依然有问题。代理为美国ip，实测无论是否使用代理或更换图片源均无法显示。

**Comment by blinkblink0** [comment]
好的好的，我打开了，但是点击图片进去出现了未知错误🙀



---原始邮件---
发件人: "itForLower"<notifications@github.com&gt;
发送时间: 2020年8月6日(周四) 凌晨0:02
收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;;
主题: Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33)




  
大佬，现在更新了好像还是打不开，图片也显示不了
  
更新之后有一个新的功能你需要打开，在设置里面有一个图片兼容的，你可能这个没开

**Comment by blinkblink0** [comment]
然后点击关注的女优，出现的也是今日更新的链接



---原始邮件---
发件人: "itForLower"<notifications@github.com&gt;
发送时间: 2020年8月6日(周四) 凌晨0:02
收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;;
主题: Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33)




  
大佬，现在更新了好像还是打不开，图片也显示不了
  
更新之后有一个新的功能你需要打开，在设置里面有一个图片兼容的，你可能这个没开

**Comment by 1458271** [comment]
> 然后点击关注的女优，出现的也是今日更新的链接
> […](#)
> ---原始邮件--- 发件人: "itForLower"<notifications@github.com&gt; 发送时间: 2020年8月6日(周四) 凌晨0:02 收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;; 主题: Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33) 大佬，现在更新了好像还是打不开，图片也显示不了 更新之后有一个新的功能你需要打开，在设置里面有一个图片兼容的，你可能这个没开 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

不太清楚，等作者回复你吧，我这边没有这样的情况。你可以尝试清除图片缓存或者卸载重装或者挂代理等等，多尝试一下，看看是什么问题

**Comment by blinkblink0** [comment]
好的，谢谢



---原始邮件---
发件人: "itForLower"<notifications@github.com&gt;
发送时间: 2020年8月6日(周四) 凌晨0:36
收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;;
主题: Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33)




  
然后点击关注的女优，出现的也是今日更新的链接
 …
 ---原始邮件--- 发件人: "itForLower"<notifications@github.com&gt; 发送时间: 2020年8月6日(周四) 凌晨0:02 收件人: "gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"blinkblink0"<1935682665@qq.com&gt;; 主题: Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33) 大佬，现在更新了好像还是打不开，图片也显示不了 更新之后有一个新的功能你需要打开，在设置里面有一个图片兼容的，你可能这个没开 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不太清楚，等作者回复你吧，我这边没有这样的情况。你可以尝试清除图片缓存或者卸载重装或者挂代理等等，多尝试一下，看看是什么问题

**Comment by 1458271** [comment]
最新反馈，“你可能也喜欢”模块正常显示，“影片收藏”部分，封面显示仍存在问题

**Comment by 1458271** [comment]
> 最新反馈，“你可能也喜欢”模块正常显示，“影片收藏”部分封面显示仍存在问题，可能是针对无🐴类型显示异常
> ![Screenshot_20200806_154143](https://user-images.githubusercontent.com/24778221/89505040-8c5eaf00-d7fb-11ea-9bca-a23764d324a8.jpg)
有以上相同问题的可以通过：取消收藏-搜索影片-重新添加收藏进行解决

**Comment by gentlemansolo** [comment]
升级3.7.4，自动切换兼容模式了

**Comment by gentlemansolo** [comment]
> > 最新反馈，“你可能也喜欢”模块正常显示，“影片收藏”部分封面显示仍存在问题，可能是针对无🐴类型显示异常
> > ![Screenshot_20200806_154143](https://user-images.githubusercontent.com/24778221/89505040-8c5eaf00-d7fb-11ea-9bca-a23764d324a8.jpg)
> > 有以上相同问题的可以通过：取消收藏-搜索影片-重新添加收藏进行解决

也可以从收藏里面点进去详情，然后点取消收藏，再收藏

**Comment by blinkblink0** [comment]
好的好的，我重新装了就可以了，感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gentlemansolo/JavRocket"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午3:56
收件人:&nbsp;"gentlemansolo/JavRocket"<JavRocket@noreply.github.com&gt;;
抄送:&nbsp;"♛Leo-Messi♛"<1935682665@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gentlemansolo/JavRocket] 出现无法加载封面的现象 (#33)





   
最新反馈，“你可能也喜欢”模块正常显示，“影片收藏”部分封面显示仍存在问题，可能是针对无🐴类型显示异常
 
 有以上相同问题的可以通过：取消收藏-搜索影片-重新添加收藏进行解决
   
也可以从收藏里面点进去详情，然后点取消收藏，再收藏
