### ISSUE TITLE
影片排序问题以及关注问题

### ISSUE THREAD

**Issue by baibai92** [gentlemansolo/JavRocket#45]
1.在使用时比对javbus官网，近期更新，最新等榜单与**官网**顺序并不一致，排序混乱，有时我会从这些榜单中浏览寻片，顺序一致可使得浏览过程更加顺畅，不会出现浏览过的影片，以及记忆位置，方便下次浏览。

2.单个影片页面无法收藏或者关注，我并不想登录javdb,只是把它当作一个本地搜索软件来使用，单个影片收藏或者关注可以方便寻片过后总结下载等操作。希望大佬能出个本地浏览记录，关注，收藏功能。总感觉多一个账号很麻烦

顺便问一下，排行榜使用的网站是什么，没找到这类影片排行榜，想去看看

**Comment by baibai92** [comment]
@gentlemansolo

**Comment by gentlemansolo** [comment]
现在查看搜索历史部分已经不需要登录了，排行榜用的是Jav_Library的
