### ISSUE TITLE
为何一定要登录才能查看足迹呢？

### ISSUE THREAD

**Issue by waddt123** [gentlemansolo/JavRocket#47]
这个功能先前就是本地版，之前因为不能手动切换源，我放弃了新版，停留在3.7.3，现在到了5.2版本，依旧还是登录才能用足迹，本地足迹功能不能使用吗？

**Comment by gentlemansolo** [comment]
因为网站需要登录才能查看足迹，本地足迹会有可能因为网站加入图片验证而无法显示的问题
