### ISSUE TITLE
建议增加blogjav预览图

### ISSUE THREAD

**Issue by a39908646** [gentlemansolo/JavRocket#55]
如题，建议增加blogjav的预览图，可以快速了解全片，还有javstore的预览图可以作为备用。

**Comment by gentlemansolo** [comment]
你的建议我会认真考虑

**Comment by ZerOri** [comment]
借个楼，为什么5.4起app体积从12M暴增到27M了？

**Comment by gentlemansolo** [comment]
> 借个楼，为什么5.4起app体积从12M暴增到27M了？

因为内置浏览器加入了广告屏蔽功能[adblock](https://github.com/adblockplus/libadblockplus-android)，所以体积大了很多

**Comment by gentlemansolo** [comment]
5.6已加入
