### ISSUE TITLE
无法打开app

### ISSUE THREAD

**Issue by dammu** [gentlemansolo/JavRocket#56]
安卓11，权限全给，打开即秒闪退。不知道是啥问题。
这个是闪退之后系统弹出的 crash log：
[https://del.dog/ufupunygni](https://del.dog/ufupunygni) 
这个是用 matlog 抓 log 过滤"cn.slh.javdb"的结果：
[https://del.dog/pepycikith.go](https://del.dog/pepycikith.go)

**Comment by gentlemansolo** [comment]
嗯，暂时没有办法解决，我这边的一加机器测试没有出现问题，初步估计是某个第三方包自带的so文件不兼容

**Comment by dammu** [comment]
> 你试试这个版本，[下载](https://gentlemansolo.lanzous.com/iitgYmdn59c)

好了！
