### ISSUE TITLE
最新版本提示异常行为被管理员封禁

### ISSUE THREAD

**Issue by gthanmon** [gentlemansolo/JavRocket#62]
更新之后总是提示  基于您的异常行为管理员禁止了你的访问

**Comment by yesterday1993** [comment]
> 更新之后总是提示 基于您的异常行为管理员禁止了你的访问

我也是这样啊，账号怎么办啊，被封了吗

**Comment by gentlemansolo** [comment]
这个得问站长，好像是他们检测到你们所用的IP异常抓取他们的数据，所以就被封了
