### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by asuna912** [gentlemansolo/JavRocket#63]
大佬，wifi连上去显示ssl handshake aborte握手失败，但是数据能直连> <

**Comment by gentlemansolo** [comment]
那应该是你wifi出问题了，你试试重启路由器吧

**Comment by asuna912** [comment]
谢谢大佬，但是我重启路由还是这样子




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gentlemansolo/JavRocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gentlemansolo/JavRocket] 谢谢 (#63)





 
那应该是你wifi出问题了，你试试重启路由器吧
