### ISSUE TITLE
最新版本依然没有解决登录的问题，收藏也还是残废

### ISSUE THREAD

**Issue by Jingyu-Yan** [gentlemansolo/JavRocket#78]
这个版本升级只看见加了广告，登录状态无法保存的问题还是没修复，收藏列表也还是只能加载一部分
另外，在看功能好像是本地存储的功能？因为登录问题清理数据之后之前列表看到的都没了

**Comment by choateyang** [comment]
安装看了，相当于javdb的安卓优化app？广告不老少。

**Comment by jettdavid23** [comment]
还是用官方版了，不折腾了。
